/// Old licensee code
///
/// # Example
///
/// ```
/// use pkmnapi_db::header::*;
///
/// let code = OldLicenseeCode::NINTENDO;
/// ```
#[derive(Debug, PartialEq)]
#[allow(non_camel_case_types)]
pub enum OldLicenseeCode {
    NONE,
    NINTENDO,
    CAPCOM,
    HOT_B,
    JALECO,
    COCONUTS,
    ELITE_SYSTEMS,
    ELECTRONIC_ARTS,
    HUDSONSOFT,
    ITC_ENTERTAINMENT,
    YANOMAN,
    CLARY,
    VIRGIN,
    PCM_COMPLETE,
    SAN_X,
    KOTOBUKI_SYSTEMS,
    SETA,
    INFOGRAMES,
    NINTENDO_2,
    BANDAI,
    GBC,
    KONAMI,
    HECTOR,
    CAPCOM_2,
    BANPRESTO,
    ENTERTAINMENT_I,
    GREMLIN,
    UBI_SOFT,
    ATLUS,
    MALIBU,
    ANGEL,
    SPECTRUM_HOLOBY,
    IREM,
    VIRGIN_2,
    MALIBU_2,
    US_GOLD,
    ABSOLUTE,
    ACCLAIM,
    ACTIVISION,
    AMERICAN_SAMMY,
    GAMETEK,
    PARK_PLACE,
    LJN,
    MATCHBOX,
    MILTON_BRADLEY,
    MINDSCAPE,
    ROMSTAR,
    NAXAT_SOFT,
    TRADEWEST,
    TITUS,
    VIRGIN_3,
    OCEAN,
    ELECTRONIC_ARTS_2,
    ELITE_SYSTEMS_2,
    ELECTRO_BRAIN,
    INFOGRAMES_3,
    INTERPLAY,
    BRODERBUND,
    SCULPTERED_SOFT,
    THE_SALES_CURVE,
    THQ,
    ACCOLADE,
    TRIFFIX_ENTERTAINMENT,
    MICROPROSE,
    KEMCO,
    MISAWA_ENTERTAINMENT,
    LOZC,
    TOKUMA_SHOTEN_I,
    BULLET_PROOF_SOFTWARE,
    VIC_TOKAI,
    APE,
    I_MAX,
    CHUN_SOFT,
    VIDEO_SYSTEM,
    TSUBURAVA,
    VARIE,
    YONEZAWA_S_PAL,
    KANEKO,
    ARC,
    NIHON_BUSSAN,
    TECMO,
    IMAGINEER,
    BANPRESTO_2,
    NOVA,
    HORI_ELECTRIC,
    BANDAI_2,
    KONAMI_2,
    KAWADA,
    TAKARA,
    TECHNOS_JAPAN,
    BRODERBUND_2,
    TOEI_ANIMATION,
    TOHO,
    NAMCO,
    ACCLAIM_2,
    ASCII_OR_NEXOFT,
    BANDAI_3,
    ENIX,
    HAL,
    SNK,
    PONY_CANYON,
    CULTURE_BRAIN_O,
    SUNSOFT,
    SONY_IMAGESOFT,
    SAMMY,
    TAITO,
    KEMCO_2,
    SQUARESOFT,
    TOKUMA_SHOTEN_I_2,
    DATA_EAST,
    TONKIN_HOUSE,
    KOEI,
    UFL,
    ULTRA,
    VAP,
    USE,
    MELDAC,
    PONY_CANYON_OR,
    ANGEL_2,
    TAITO_2,
    SOFEL,
    QUEST,
    SIGMA_ENTERPRISES,
    ASK_KODANSHA,
    NAXAT_SOFT_2,
    COPYA_SYSTEMS,
    BANPRESTO_3,
    TOMY,
    LJN_2,
    NCS,
    HUMAN,
    ALTRON,
    JALECO_2,
    TOWACHIKI,
    UUTAKA,
    VARIE_2,
    EPOCH,
    ATHENA,
    ASMIK,
    NATSUME,
    KING_RECORDS,
    ATLUS_2,
    EPIC_SONY_RECORDS,
    IGS,
    A_WAVE,
    EXTREME_ENTERTAINMENT,
    LJN_3,
}

impl From<u8> for OldLicenseeCode {
    /// Convert u8 to OldLicenseeCode
    ///
    /// # Example
    ///
    /// ```
    /// use pkmnapi_db::header::*;
    ///
    /// let code = OldLicenseeCode::from(0x01);
    ///
    /// assert_eq!(code, OldLicenseeCode::NINTENDO);
    /// ```
    fn from(old_licensee_code: u8) -> Self {
        match old_licensee_code {
            0x01 => OldLicenseeCode::NINTENDO,
            0x08 => OldLicenseeCode::CAPCOM,
            0x09 => OldLicenseeCode::HOT_B,
            0x0A => OldLicenseeCode::JALECO,
            0x0B => OldLicenseeCode::COCONUTS,
            0x0C => OldLicenseeCode::ELITE_SYSTEMS,
            0x13 => OldLicenseeCode::ELECTRONIC_ARTS,
            0x18 => OldLicenseeCode::HUDSONSOFT,
            0x19 => OldLicenseeCode::ITC_ENTERTAINMENT,
            0x1A => OldLicenseeCode::YANOMAN,
            0x1D => OldLicenseeCode::CLARY,
            0x1F => OldLicenseeCode::VIRGIN,
            0x24 => OldLicenseeCode::PCM_COMPLETE,
            0x25 => OldLicenseeCode::SAN_X,
            0x28 => OldLicenseeCode::KOTOBUKI_SYSTEMS,
            0x29 => OldLicenseeCode::SETA,
            0x30 => OldLicenseeCode::INFOGRAMES,
            0x31 => OldLicenseeCode::NINTENDO_2,
            0x32 => OldLicenseeCode::BANDAI,
            0x33 => OldLicenseeCode::GBC,
            0x34 => OldLicenseeCode::KONAMI,
            0x35 => OldLicenseeCode::HECTOR,
            0x38 => OldLicenseeCode::CAPCOM_2,
            0x39 => OldLicenseeCode::BANPRESTO,
            0x3C => OldLicenseeCode::ENTERTAINMENT_I,
            0x3E => OldLicenseeCode::GREMLIN,
            0x41 => OldLicenseeCode::UBI_SOFT,
            0x42 => OldLicenseeCode::ATLUS,
            0x44 => OldLicenseeCode::MALIBU,
            0x46 => OldLicenseeCode::ANGEL,
            0x47 => OldLicenseeCode::SPECTRUM_HOLOBY,
            0x49 => OldLicenseeCode::IREM,
            0x4A => OldLicenseeCode::VIRGIN_2,
            0x4D => OldLicenseeCode::MALIBU_2,
            0x4F => OldLicenseeCode::US_GOLD,
            0x50 => OldLicenseeCode::ABSOLUTE,
            0x51 => OldLicenseeCode::ACCLAIM,
            0x52 => OldLicenseeCode::ACTIVISION,
            0x53 => OldLicenseeCode::AMERICAN_SAMMY,
            0x54 => OldLicenseeCode::GAMETEK,
            0x55 => OldLicenseeCode::PARK_PLACE,
            0x56 => OldLicenseeCode::LJN,
            0x57 => OldLicenseeCode::MATCHBOX,
            0x59 => OldLicenseeCode::MILTON_BRADLEY,
            0x5A => OldLicenseeCode::MINDSCAPE,
            0x5B => OldLicenseeCode::ROMSTAR,
            0x5C => OldLicenseeCode::NAXAT_SOFT,
            0x5D => OldLicenseeCode::TRADEWEST,
            0x60 => OldLicenseeCode::TITUS,
            0x61 => OldLicenseeCode::VIRGIN_3,
            0x67 => OldLicenseeCode::OCEAN,
            0x69 => OldLicenseeCode::ELECTRONIC_ARTS_2,
            0x6E => OldLicenseeCode::ELITE_SYSTEMS_2,
            0x6F => OldLicenseeCode::ELECTRO_BRAIN,
            0x70 => OldLicenseeCode::INFOGRAMES_3,
            0x71 => OldLicenseeCode::INTERPLAY,
            0x72 => OldLicenseeCode::BRODERBUND,
            0x73 => OldLicenseeCode::SCULPTERED_SOFT,
            0x75 => OldLicenseeCode::THE_SALES_CURVE,
            0x78 => OldLicenseeCode::THQ,
            0x79 => OldLicenseeCode::ACCOLADE,
            0x7A => OldLicenseeCode::TRIFFIX_ENTERTAINMENT,
            0x7C => OldLicenseeCode::MICROPROSE,
            0x7F => OldLicenseeCode::KEMCO,
            0x80 => OldLicenseeCode::MISAWA_ENTERTAINMENT,
            0x83 => OldLicenseeCode::LOZC,
            0x86 => OldLicenseeCode::TOKUMA_SHOTEN_I,
            0x8B => OldLicenseeCode::BULLET_PROOF_SOFTWARE,
            0x8C => OldLicenseeCode::VIC_TOKAI,
            0x8E => OldLicenseeCode::APE,
            0x8F => OldLicenseeCode::I_MAX,
            0x91 => OldLicenseeCode::CHUN_SOFT,
            0x92 => OldLicenseeCode::VIDEO_SYSTEM,
            0x93 => OldLicenseeCode::TSUBURAVA,
            0x95 => OldLicenseeCode::VARIE,
            0x96 => OldLicenseeCode::YONEZAWA_S_PAL,
            0x97 => OldLicenseeCode::KANEKO,
            0x99 => OldLicenseeCode::ARC,
            0x9A => OldLicenseeCode::NIHON_BUSSAN,
            0x9B => OldLicenseeCode::TECMO,
            0x9C => OldLicenseeCode::IMAGINEER,
            0x9D => OldLicenseeCode::BANPRESTO_2,
            0x9F => OldLicenseeCode::NOVA,
            0xA1 => OldLicenseeCode::HORI_ELECTRIC,
            0xA2 => OldLicenseeCode::BANDAI_2,
            0xA4 => OldLicenseeCode::KONAMI_2,
            0xA6 => OldLicenseeCode::KAWADA,
            0xA7 => OldLicenseeCode::TAKARA,
            0xA9 => OldLicenseeCode::TECHNOS_JAPAN,
            0xAA => OldLicenseeCode::BRODERBUND_2,
            0xAC => OldLicenseeCode::TOEI_ANIMATION,
            0xAD => OldLicenseeCode::TOHO,
            0xAF => OldLicenseeCode::NAMCO,
            0xB0 => OldLicenseeCode::ACCLAIM_2,
            0xB1 => OldLicenseeCode::ASCII_OR_NEXOFT,
            0xB2 => OldLicenseeCode::BANDAI_3,
            0xB4 => OldLicenseeCode::ENIX,
            0xB6 => OldLicenseeCode::HAL,
            0xB7 => OldLicenseeCode::SNK,
            0xB9 => OldLicenseeCode::PONY_CANYON,
            0xBA => OldLicenseeCode::CULTURE_BRAIN_O,
            0xBB => OldLicenseeCode::SUNSOFT,
            0xBD => OldLicenseeCode::SONY_IMAGESOFT,
            0xBF => OldLicenseeCode::SAMMY,
            0xC0 => OldLicenseeCode::TAITO,
            0xC2 => OldLicenseeCode::KEMCO_2,
            0xC3 => OldLicenseeCode::SQUARESOFT,
            0xC4 => OldLicenseeCode::TOKUMA_SHOTEN_I_2,
            0xC5 => OldLicenseeCode::DATA_EAST,
            0xC6 => OldLicenseeCode::TONKIN_HOUSE,
            0xC8 => OldLicenseeCode::KOEI,
            0xC9 => OldLicenseeCode::UFL,
            0xCA => OldLicenseeCode::ULTRA,
            0xCB => OldLicenseeCode::VAP,
            0xCC => OldLicenseeCode::USE,
            0xCD => OldLicenseeCode::MELDAC,
            0xCE => OldLicenseeCode::PONY_CANYON_OR,
            0xCF => OldLicenseeCode::ANGEL_2,
            0xD0 => OldLicenseeCode::TAITO_2,
            0xD1 => OldLicenseeCode::SOFEL,
            0xD2 => OldLicenseeCode::QUEST,
            0xD3 => OldLicenseeCode::SIGMA_ENTERPRISES,
            0xD4 => OldLicenseeCode::ASK_KODANSHA,
            0xD6 => OldLicenseeCode::NAXAT_SOFT_2,
            0xD7 => OldLicenseeCode::COPYA_SYSTEMS,
            0xD9 => OldLicenseeCode::BANPRESTO_3,
            0xDA => OldLicenseeCode::TOMY,
            0xDB => OldLicenseeCode::LJN_2,
            0xDD => OldLicenseeCode::NCS,
            0xDE => OldLicenseeCode::HUMAN,
            0xDF => OldLicenseeCode::ALTRON,
            0xE0 => OldLicenseeCode::JALECO_2,
            0xE1 => OldLicenseeCode::TOWACHIKI,
            0xE2 => OldLicenseeCode::UUTAKA,
            0xE3 => OldLicenseeCode::VARIE_2,
            0xE5 => OldLicenseeCode::EPOCH,
            0xE7 => OldLicenseeCode::ATHENA,
            0xE8 => OldLicenseeCode::ASMIK,
            0xE9 => OldLicenseeCode::NATSUME,
            0xEA => OldLicenseeCode::KING_RECORDS,
            0xEB => OldLicenseeCode::ATLUS_2,
            0xEC => OldLicenseeCode::EPIC_SONY_RECORDS,
            0xEE => OldLicenseeCode::IGS,
            0xF0 => OldLicenseeCode::A_WAVE,
            0xF3 => OldLicenseeCode::EXTREME_ENTERTAINMENT,
            0xFF => OldLicenseeCode::LJN_3,
            _ => OldLicenseeCode::NONE,
        }
    }
}
