use pkmnapi_db::*;
use std::fs;

mod common;

macro_rules! get_pokemon_pic_test {
    ($test_name:ident, $pokedex_id:expr, $pic_face:expr, $pic_filename:expr) => {
        #[test]
        #[ignore]
        #[allow(non_snake_case)]
        fn $test_name() {
            let db = common::load_rom();
            let pic_data = fs::read($pic_filename).unwrap();

            match db.get_pokemon_pic(&$pokedex_id, &$pic_face) {
                Ok(pic) => assert_eq!(
                    pic.to_png(false).unwrap(),
                    pic_data,
                    "Searched for Pokédex ID: {}",
                    $pokedex_id
                ),
                Err(_) => panic!(format!("Could not find Pokédex ID: {}", $pokedex_id)),
            };
        }
    };
}

get_pokemon_pic_test!(
    get_pokemon_pic_front_1,
    1,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-1.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_1,
    1,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-1.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_2,
    2,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-2.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_2,
    2,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-2.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_3,
    3,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-3.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_3,
    3,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-3.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_4,
    4,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-4.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_4,
    4,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-4.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_5,
    5,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-5.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_5,
    5,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-5.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_6,
    6,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-6.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_6,
    6,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-6.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_7,
    7,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-7.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_7,
    7,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-7.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_8,
    8,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-8.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_8,
    8,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-8.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_9,
    9,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-9.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_9,
    9,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-9.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_10,
    10,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-10.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_10,
    10,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-10.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_11,
    11,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-11.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_11,
    11,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-11.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_12,
    12,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-12.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_12,
    12,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-12.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_13,
    13,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-13.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_13,
    13,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-13.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_14,
    14,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-14.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_14,
    14,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-14.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_15,
    15,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-15.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_15,
    15,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-15.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_16,
    16,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-16.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_16,
    16,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-16.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_17,
    17,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-17.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_17,
    17,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-17.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_18,
    18,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-18.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_18,
    18,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-18.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_19,
    19,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-19.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_19,
    19,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-19.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_20,
    20,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-20.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_20,
    20,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-20.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_21,
    21,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-21.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_21,
    21,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-21.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_22,
    22,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-22.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_22,
    22,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-22.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_23,
    23,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-23.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_23,
    23,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-23.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_24,
    24,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-24.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_24,
    24,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-24.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_25,
    25,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-25.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_25,
    25,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-25.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_26,
    26,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-26.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_26,
    26,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-26.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_27,
    27,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-27.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_27,
    27,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-27.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_28,
    28,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-28.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_28,
    28,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-28.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_29,
    29,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-29.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_29,
    29,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-29.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_30,
    30,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-30.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_30,
    30,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-30.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_31,
    31,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-31.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_31,
    31,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-31.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_32,
    32,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-32.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_32,
    32,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-32.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_33,
    33,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-33.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_33,
    33,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-33.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_34,
    34,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-34.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_34,
    34,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-34.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_35,
    35,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-35.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_35,
    35,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-35.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_36,
    36,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-36.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_36,
    36,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-36.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_37,
    37,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-37.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_37,
    37,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-37.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_38,
    38,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-38.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_38,
    38,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-38.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_39,
    39,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-39.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_39,
    39,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-39.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_40,
    40,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-40.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_40,
    40,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-40.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_41,
    41,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-41.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_41,
    41,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-41.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_42,
    42,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-42.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_42,
    42,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-42.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_43,
    43,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-43.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_43,
    43,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-43.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_44,
    44,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-44.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_44,
    44,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-44.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_45,
    45,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-45.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_45,
    45,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-45.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_46,
    46,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-46.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_46,
    46,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-46.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_47,
    47,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-47.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_47,
    47,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-47.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_48,
    48,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-48.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_48,
    48,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-48.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_49,
    49,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-49.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_49,
    49,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-49.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_50,
    50,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-50.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_50,
    50,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-50.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_51,
    51,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-51.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_51,
    51,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-51.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_52,
    52,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-52.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_52,
    52,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-52.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_53,
    53,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-53.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_53,
    53,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-53.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_54,
    54,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-54.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_54,
    54,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-54.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_55,
    55,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-55.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_55,
    55,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-55.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_56,
    56,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-56.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_56,
    56,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-56.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_57,
    57,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-57.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_57,
    57,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-57.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_58,
    58,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-58.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_58,
    58,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-58.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_59,
    59,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-59.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_59,
    59,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-59.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_60,
    60,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-60.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_60,
    60,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-60.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_61,
    61,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-61.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_61,
    61,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-61.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_62,
    62,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-62.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_62,
    62,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-62.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_63,
    63,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-63.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_63,
    63,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-63.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_64,
    64,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-64.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_64,
    64,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-64.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_65,
    65,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-65.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_65,
    65,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-65.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_66,
    66,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-66.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_66,
    66,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-66.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_67,
    67,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-67.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_67,
    67,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-67.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_68,
    68,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-68.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_68,
    68,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-68.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_69,
    69,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-69.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_69,
    69,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-69.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_70,
    70,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-70.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_70,
    70,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-70.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_71,
    71,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-71.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_71,
    71,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-71.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_72,
    72,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-72.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_72,
    72,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-72.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_73,
    73,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-73.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_73,
    73,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-73.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_74,
    74,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-74.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_74,
    74,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-74.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_75,
    75,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-75.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_75,
    75,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-75.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_76,
    76,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-76.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_76,
    76,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-76.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_77,
    77,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-77.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_77,
    77,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-77.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_78,
    78,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-78.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_78,
    78,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-78.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_79,
    79,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-79.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_79,
    79,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-79.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_80,
    80,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-80.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_80,
    80,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-80.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_81,
    81,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-81.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_81,
    81,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-81.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_82,
    82,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-82.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_82,
    82,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-82.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_83,
    83,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-83.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_83,
    83,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-83.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_84,
    84,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-84.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_84,
    84,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-84.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_85,
    85,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-85.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_85,
    85,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-85.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_86,
    86,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-86.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_86,
    86,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-86.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_87,
    87,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-87.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_87,
    87,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-87.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_88,
    88,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-88.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_88,
    88,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-88.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_89,
    89,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-89.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_89,
    89,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-89.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_90,
    90,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-90.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_90,
    90,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-90.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_91,
    91,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-91.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_91,
    91,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-91.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_92,
    92,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-92.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_92,
    92,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-92.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_93,
    93,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-93.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_93,
    93,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-93.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_94,
    94,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-94.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_94,
    94,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-94.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_95,
    95,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-95.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_95,
    95,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-95.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_96,
    96,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-96.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_96,
    96,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-96.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_97,
    97,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-97.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_97,
    97,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-97.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_98,
    98,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-98.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_98,
    98,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-98.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_99,
    99,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-99.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_99,
    99,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-99.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_100,
    100,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-100.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_100,
    100,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-100.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_101,
    101,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-101.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_101,
    101,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-101.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_102,
    102,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-102.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_102,
    102,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-102.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_103,
    103,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-103.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_103,
    103,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-103.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_104,
    104,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-104.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_104,
    104,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-104.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_105,
    105,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-105.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_105,
    105,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-105.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_106,
    106,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-106.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_106,
    106,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-106.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_107,
    107,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-107.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_107,
    107,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-107.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_108,
    108,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-108.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_108,
    108,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-108.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_109,
    109,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-109.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_109,
    109,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-109.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_110,
    110,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-110.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_110,
    110,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-110.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_111,
    111,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-111.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_111,
    111,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-111.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_112,
    112,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-112.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_112,
    112,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-112.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_113,
    113,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-113.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_113,
    113,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-113.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_114,
    114,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-114.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_114,
    114,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-114.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_115,
    115,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-115.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_115,
    115,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-115.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_116,
    116,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-116.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_116,
    116,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-116.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_117,
    117,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-117.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_117,
    117,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-117.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_118,
    118,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-118.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_118,
    118,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-118.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_119,
    119,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-119.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_119,
    119,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-119.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_120,
    120,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-120.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_120,
    120,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-120.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_121,
    121,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-121.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_121,
    121,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-121.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_122,
    122,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-122.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_122,
    122,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-122.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_123,
    123,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-123.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_123,
    123,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-123.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_124,
    124,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-124.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_124,
    124,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-124.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_125,
    125,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-125.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_125,
    125,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-125.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_126,
    126,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-126.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_126,
    126,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-126.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_127,
    127,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-127.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_127,
    127,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-127.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_128,
    128,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-128.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_128,
    128,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-128.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_129,
    129,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-129.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_129,
    129,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-129.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_130,
    130,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-130.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_130,
    130,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-130.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_131,
    131,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-131.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_131,
    131,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-131.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_132,
    132,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-132.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_132,
    132,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-132.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_133,
    133,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-133.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_133,
    133,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-133.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_134,
    134,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-134.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_134,
    134,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-134.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_135,
    135,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-135.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_135,
    135,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-135.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_136,
    136,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-136.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_136,
    136,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-136.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_137,
    137,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-137.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_137,
    137,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-137.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_138,
    138,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-138.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_138,
    138,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-138.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_139,
    139,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-139.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_139,
    139,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-139.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_140,
    140,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-140.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_140,
    140,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-140.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_141,
    141,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-141.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_141,
    141,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-141.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_142,
    142,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-142.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_142,
    142,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-142.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_143,
    143,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-143.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_143,
    143,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-143.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_144,
    144,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-144.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_144,
    144,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-144.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_145,
    145,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-145.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_145,
    145,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-145.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_146,
    146,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-146.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_146,
    146,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-146.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_147,
    147,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-147.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_147,
    147,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-147.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_148,
    148,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-148.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_148,
    148,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-148.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_149,
    149,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-149.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_149,
    149,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-149.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_150,
    150,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-150.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_150,
    150,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-150.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_front_151,
    151,
    PokemonPicFace::FRONT,
    "../secrets/data/pokemon_pic/front-151.png"
);
get_pokemon_pic_test!(
    get_pokemon_pic_back_151,
    151,
    PokemonPicFace::BACK,
    "../secrets/data/pokemon_pic/back-151.png"
);
